### ISSUE TITLE
feature request: ability to login to hauk

### ISSUE THREAD

**Issue by pvagner** [tuffnerdstuff/hauk-snitch#11]
I would like to use this with a few friends. Some of us are using hauk directly while others are only using owntracks.
I would like to password protect the hauk instance so it does not use empty password.
Would it be possible to add password or username with password logging to hauk please?

**Comment by tuffnerdstuff** [comment]
Good point, I'll see what I can do.

**Comment by tuffnerdstuff** [comment]
Funny, I had almost everything in place already, but as I do not use authentication I forgot about it :smile: If you want to test the feature, fell free to check out the branch [/feature/authentication](https://github.com/tuffnerdstuff/hauk-snitch/tree/feature/authentication). I also updated the README.md explaining how to configure hauk-snitch in this case.

**Comment by cyrinux** [comment]
This can be close I think, its merge @pvagner thanks @tuffnerdstuff 👍🏻
