### ISSUE TITLE
Docker image on docker hub ?

### ISSUE THREAD

**Issue by cyrinux** [tuffnerdstuff/hauk-snitch#15]
Hey @tuffnerdstuff ,

Now the project is pretty and use by several people, could you add a tiny github action maybe to build and push this cool project on docker hub ? 🙏🏻 

I would be happy to simplify my stack by just using an external image 😃

**Comment by tuffnerdstuff** [comment]
Good idea! I'll look into it. It was not important for me, yet, as my test, dev and production server are the same 😁

**Comment by tuffnerdstuff** [comment]
I added an action for that. Images will now be pushed to https://hub.docker.com/r/tuffnerdstuff/hauk-snitch. Let me know if that works for you!

**Comment by cyrinux** [comment]
will try asap, thanks you !

**Comment by cyrinux** [comment]
It works well 😊
