### ISSUE TITLE
Combination of tls & suggested port number in template-config might be confusing

### ISSUE THREAD

**Issue by jpmens** [tuffnerdstuff/hauk-snitch#6]
I notice in [template-config.toml](template-config.toml) that the MQTT configuration specifies `tls=true` for `port=1883`. I realize this is but an example configuration, but I could imagine people stumbling over this and not realizing that 1883 defaults to plain MQTT without TLS.

Might I suggest specifying `tls = false` in the example?

**Comment by tuffnerdstuff** [comment]
Good catch! I took over the basic config from my setup, where I switched over to TLS but kept the port.

**Comment by tuffnerdstuff** [comment]
Done
