### ISSUE TITLE
Email notifications are likelly to be flagged as spam

### ISSUE THREAD

**Issue by pvagner** [tuffnerdstuff/hauk-snitch#9]
Hello,
When sending out notifications about new sessions being created, the email messages are missing many standard message headers.
Here is the rspamd report when scanning such message:
```X-Rspamd-Report: MISSING_FROM(2) MISSING_DATE(1) MIME_GOOD(-0.1) MISSING_MID(2.5) MISSING_TO(2)```

**Comment by tuffnerdstuff** [comment]
Good point, I'll add those properties when I've got time to get back into the project. Currently it works for me in Google Mail, because once I "unflag" a message as Spam, new ones end up in the Inbox.
